export const plans = [
	{
		id: 1,
		tagline: 'Best For Daily Usage',
		price: 10,
		features: [
			'200GB Local Data',
			'1GB Data Roaming (MYS/IDN)',
			'1000 Local Mins',
			'100 Local SMS',
			'Unlimited Local Incoming Call',
			'Free Caller ID',
		],
		isFeatured: false,
	},
	{
		id: 2,
		tagline: 'Best For Calling',
		price: 12,
		features: [
			'200GB Local Data',
			'1GB Data Roaming (MYS/IDN)',
			'350 Mins IDD',
			'2000 Local Mins',
			'200 Local SMS',
			'Unlimited Local Incoming Call',
			'Free Caller ID',
		],
		isFeatured: true,
	},
	{
		id: 3,
		tagline: 'Road Trip Bestie',
		price: 15,
		features: [
			'300GB Local Data',
			'3GB Data Roaming (MYS/IDN/THA)',
			'1000 Local Mins',
			'100 Local SMS',
			'Unlimited Local Incoming Call',
			'Free Caller ID',
		],
		isFeatured: false,
	},
	{
		id: 4,
		tagline: 'Ample Data Roaming',
		price: 20,
		features: [
			'500GB Local Data',
			'1GB Data Roaming Per Day (MYS/IDN/THA/KHM/HKG/BGD/TWN)',
			'200Mins IDD',
			'1000 Local Mins',
			'100 Local SMS',
			'Unlimited Local Incoming Call',
			'Free Caller ID',
		],
		isFeatured: false,
	},
];
